spring:
  application:
    name: spring-boot-blazebit
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true


#logging:
#  level:
#    org.hibernate.SQL: DEBUG